"""initial: 13 tables from round 2

Revision ID: 87c9044df1b3
Revises: 
Create Date: 2026-08-05 23:52:34.781513
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c9044df1b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('crawler_name', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='crawlstatus'), nullable=False),
    sa.Column('items_fetched', sa.Integer(), nullable=False),
    sa.Column('items_saved', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_crawler_name'), 'crawl_jobs', ['crawler_name'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_platform'), 'crawl_jobs', ['platform'], unique=False)
    op.create_table('credit_cards',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bank', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('network', sa.Enum('UNIONPAY', 'VISA', 'MASTERCARD', 'AMEX', 'JCB', name='cardnetwork'), nullable=False),
    sa.Column('level', sa.Enum('CLASSIC', 'GOLD', 'PLATINUM', 'DIAMOND', 'SIGNATURE', 'INFINITE', name='cardlevel'), nullable=False),
    sa.Column('annual_fee', sa.String(length=64), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_cards_bank'), 'credit_cards', ['bank'], unique=False)
    op.create_table('merchant_activities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('platform', sa.String(length=9), nullable=False),
    sa.Column('merchant_name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=True),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('activity_price', sa.Float(), nullable=True),
    sa.Column('discount_description', sa.Text(), nullable=False),
    sa.Column('usage_conditions', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('app_url', sa.String(length=512), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_activities_category'), 'merchant_activities', ['category'], unique=False)
    op.create_index(op.f('ix_merchant_activities_merchant_name'), 'merchant_activities', ['merchant_name'], unique=False)
    op.create_index(op.f('ix_merchant_activities_platform'), 'merchant_activities', ['platform'], unique=False)
    op.create_index(op.f('ix_merchant_activities_product_name'), 'merchant_activities', ['product_name'], unique=False)
    op.create_index(op.f('ix_merchant_activities_status'), 'merchant_activities', ['status'], unique=False)
    op.create_index(op.f('ix_merchant_activities_title'), 'merchant_activities', ['title'], unique=False)
    op.create_table('user_cards',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('issue_date', sa.String(length=7), nullable=True),
    sa.Column('expire_date', sa.String(length=7), nullable=True),
    sa.Column('annual_fee_condition', sa.String(length=256), nullable=True),
    sa.Column('annual_fee_waived', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cards_card_id'), 'user_cards', ['card_id'], unique=False)
    op.create_index(op.f('ix_user_cards_user_id'), 'user_cards', ['user_id'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_title', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorites_target_id'), 'user_favorites', ['target_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.create_table('user_search_history',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('keyword', sa.String(length=256), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_search_history_user_id'), 'user_search_history', ['user_id'], unique=False)
    op.create_table('bill_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('user_card_id', sa.String(length=64), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=True),
    sa.Column('statement_date', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Integer(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('min_payment', sa.Float(), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('usage_rate', sa.Float(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.id'], ),
    sa.ForeignKeyConstraint(['user_card_id'], ['user_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_records_user_card_id'), 'bill_records', ['user_card_id'], unique=False)
    op.create_index(op.f('ix_bill_records_user_id'), 'bill_records', ['user_id'], unique=False)
    op.create_table('card_benefits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('benefit_type', sa.Enum('CASHBACK', 'POINTS', 'DISCOUNT', 'BUY_ONE_GET_ONE', 'FREE_GIFT', 'LOUNGE', 'PRIORITY', 'INSURANCE', 'OTHER', name='benefittype'), nullable=False),
    sa.Column('category', sa.Enum('DINING', 'COFFEE', 'SHOPPING', 'ONLINE', 'TRAVEL', 'PETROL', 'ENTERTAINMENT', 'GROCERY', 'BILL', 'GENERAL', name='benefitcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('value_text', sa.String(length=128), nullable=True),
    sa.Column('points_per_yuan', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('cashback_percent', sa.Float(), nullable=True),
    sa.Column('usage_limit', sa.String(length=256), nullable=True),
    sa.Column('merchant_tags', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_benefits_card_id'), 'card_benefits', ['card_id'], unique=False)
    op.create_table('expense_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('user_card_id', sa.String(length=64), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('merchant', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('is_refund', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_card_id'], ['user_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_records_user_card_id'), 'expense_records', ['user_card_id'], unique=False)
    op.create_index(op.f('ix_expense_records_user_id'), 'expense_records', ['user_id'], unique=False)
    op.create_table('redemption_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=True),
    sa.Column('item_name', sa.String(length=256), nullable=False),
    sa.Column('merchant_name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('points_required', sa.Integer(), nullable=False),
    sa.Column('cash_value', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redemption_items_card_id'), 'redemption_items', ['card_id'], unique=False)
    op.create_index(op.f('ix_redemption_items_category'), 'redemption_items', ['category'], unique=False)
    op.create_index(op.f('ix_redemption_items_item_name'), 'redemption_items', ['item_name'], unique=False)
    op.create_table('user_redemption_overrides',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('user_card_id', sa.String(length=64), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=True),
    sa.Column('item_name', sa.String(length=256), nullable=False),
    sa.Column('merchant_name', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('points_required', sa.Float(), nullable=False),
    sa.Column('cash_value', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_card_id'], ['user_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_redemption_overrides_user_card_id'), 'user_redemption_overrides', ['user_card_id'], unique=False)
    op.create_index(op.f('ix_user_redemption_overrides_user_id'), 'user_redemption_overrides', ['user_id'], unique=False)
    op.create_table('benefit_usage_tracks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('user_card_id', sa.String(length=64), nullable=False),
    sa.Column('benefit_id', sa.String(length=64), nullable=False),
    sa.Column('benefit_title', sa.String(length=256), nullable=False),
    sa.Column('monthly_limit', sa.Integer(), nullable=True),
    sa.Column('used_this_month', sa.Integer(), nullable=False),
    sa.Column('last_used_date', sa.Date(), nullable=True),
    sa.Column('last_reset_month', sa.String(length=7), nullable=True),
    sa.Column('year_limit', sa.Integer(), nullable=True),
    sa.Column('used_this_year', sa.Integer(), nullable=False),
    sa.Column('total_used', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['benefit_id'], ['card_benefits.id'], ),
    sa.ForeignKeyConstraint(['user_card_id'], ['user_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefit_usage_tracks_benefit_id'), 'benefit_usage_tracks', ['benefit_id'], unique=False)
    op.create_index(op.f('ix_benefit_usage_tracks_user_card_id'), 'benefit_usage_tracks', ['user_card_id'], unique=False)
    op.create_index(op.f('ix_benefit_usage_tracks_user_id'), 'benefit_usage_tracks', ['user_id'], unique=False)
    op.create_table('user_benefit_overrides',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('user_card_id', sa.String(length=64), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=True),
    sa.Column('benefit_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('benefit_type', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('cashback_percent', sa.Float(), nullable=True),
    sa.Column('points_per_yuan', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=128), nullable=True),
    sa.Column('usage_limit', sa.String(length=256), nullable=True),
    sa.Column('merchant_tags', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['benefit_id'], ['card_benefits.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.id'], ),
    sa.ForeignKeyConstraint(['user_card_id'], ['user_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_benefit_overrides_user_card_id'), 'user_benefit_overrides', ['user_card_id'], unique=False)
    op.create_index(op.f('ix_user_benefit_overrides_user_id'), 'user_benefit_overrides', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_benefit_overrides_user_id'), table_name='user_benefit_overrides')
    op.drop_index(op.f('ix_user_benefit_overrides_user_card_id'), table_name='user_benefit_overrides')
    op.drop_table('user_benefit_overrides')
    op.drop_index(op.f('ix_benefit_usage_tracks_user_id'), table_name='benefit_usage_tracks')
    op.drop_index(op.f('ix_benefit_usage_tracks_user_card_id'), table_name='benefit_usage_tracks')
    op.drop_index(op.f('ix_benefit_usage_tracks_benefit_id'), table_name='benefit_usage_tracks')
    op.drop_table('benefit_usage_tracks')
    op.drop_index(op.f('ix_user_redemption_overrides_user_id'), table_name='user_redemption_overrides')
    op.drop_index(op.f('ix_user_redemption_overrides_user_card_id'), table_name='user_redemption_overrides')
    op.drop_table('user_redemption_overrides')
    op.drop_index(op.f('ix_redemption_items_item_name'), table_name='redemption_items')
    op.drop_index(op.f('ix_redemption_items_category'), table_name='redemption_items')
    op.drop_index(op.f('ix_redemption_items_card_id'), table_name='redemption_items')
    op.drop_table('redemption_items')
    op.drop_index(op.f('ix_expense_records_user_id'), table_name='expense_records')
    op.drop_index(op.f('ix_expense_records_user_card_id'), table_name='expense_records')
    op.drop_table('expense_records')
    op.drop_index(op.f('ix_card_benefits_card_id'), table_name='card_benefits')
    op.drop_table('card_benefits')
    op.drop_index(op.f('ix_bill_records_user_id'), table_name='bill_records')
    op.drop_index(op.f('ix_bill_records_user_card_id'), table_name='bill_records')
    op.drop_table('bill_records')
    op.drop_index(op.f('ix_user_search_history_user_id'), table_name='user_search_history')
    op.drop_table('user_search_history')
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_target_id'), table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_user_cards_user_id'), table_name='user_cards')
    op.drop_index(op.f('ix_user_cards_card_id'), table_name='user_cards')
    op.drop_table('user_cards')
    op.drop_index(op.f('ix_merchant_activities_title'), table_name='merchant_activities')
    op.drop_index(op.f('ix_merchant_activities_status'), table_name='merchant_activities')
    op.drop_index(op.f('ix_merchant_activities_product_name'), table_name='merchant_activities')
    op.drop_index(op.f('ix_merchant_activities_platform'), table_name='merchant_activities')
    op.drop_index(op.f('ix_merchant_activities_merchant_name'), table_name='merchant_activities')
    op.drop_index(op.f('ix_merchant_activities_category'), table_name='merchant_activities')
    op.drop_table('merchant_activities')
    op.drop_index(op.f('ix_credit_cards_bank'), table_name='credit_cards')
    op.drop_table('credit_cards')
    op.drop_index(op.f('ix_crawl_jobs_platform'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_crawler_name'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    # ### end Alembic commands ###
