"""商家活动种子数据 — 每条活动含 source_url（网页）和 app_url（App 深链直跳下单页）。

各平台深链格式说明（生产环境由爬虫实时抓取真实链接）：
- 抖音: snssdk1128:// 或 douyin:// 唤起App → 团购页
- 美团: imeituan://www.meituan.com/或直接打开小程序
- 饿了么: eleme:// 唤起App
- 支付宝: alipays://platformapi/startapp 唤起小程序
- 京东: openApp.jdMobile:// 唤起App → 商品页
- 滴滴: diditaxi:// 唤起App
- 淘宝: taobao:// 唤起App → 搜索/商品页

手机访问时点「去下单」优先尝试 app_url 唤起App，失败则回退 source_url 网页。
桌面端直接打开 source_url。
"""
from datetime import datetime, timedelta

_NOW = datetime.now()


def _days(n, hour=23, minute=59, second=59):
    return (_NOW + timedelta(days=n)).replace(hour=hour, minute=minute, second=second)


ACTIVITIES = [
    # ===================================================
    # 瑞幸咖啡 (6 platforms)
    # ===================================================
    {
        "id": "act_dy_luckin_5",
        "title": "瑞幸咖啡抖音券 9.9元任选2杯",
        "platform": "抖音",
        "merchant_name": "瑞幸咖啡",
        "category": "咖啡茶饮",
        "product_name": "瑞幸咖啡任选2杯券",
        "original_price": 60.0,
        "activity_price": 9.9,
        "discount_description": "9.9元任选2杯，相当于4.95元/杯",
        "usage_conditions": "抖音App下单，到店自取",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/%E7%91%9E%E5%B9%B8%E5%92%96%E5%95%A1%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E7%91%9E%E5%B9%B8%E5%92%96%E5%95%A1%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_mt_luckin_15",
        "title": "瑞幸咖啡美团券 15元3杯",
        "platform": "美团",
        "merchant_name": "瑞幸咖啡",
        "category": "咖啡茶饮",
        "product_name": "瑞幸咖啡3杯套餐",
        "original_price": 60.0,
        "activity_price": 15.0,
        "discount_description": "15元3杯，相当于5元/杯",
        "usage_conditions": "美团App下单，到店自取",
        "valid_to": _days(5),
        "source_url": "https://i.meituan.com/s/%E7%91%9E%E5%B9%B8%E5%92%96%E5%95%A1/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=瑞幸咖啡",
        "source_type": "manual",
    },
    {
        "id": "act_al_luckin_19",
        "title": "瑞幸咖啡支付宝优惠券 19元2杯",
        "platform": "支付宝",
        "merchant_name": "瑞幸咖啡",
        "category": "咖啡茶饮",
        "product_name": "瑞幸咖啡2杯券",
        "original_price": 50.0,
        "activity_price": 19.0,
        "discount_description": "19元2杯，相当于9.5元/杯",
        "usage_conditions": "支付宝小程序下单",
        "valid_to": _days(10),
        "source_url": "https://render.alipay.com/p/s/luckin",
        "app_url": "alipays://platformapi/startapp?appId=20001&page=pages/home/index&query=merchant%3Dluckin",
        "source_type": "manual",
    },
    {
        "id": "act_jd_coffee_49",
        "title": "京东瑞幸 49.9元10杯卡",
        "platform": "京东",
        "merchant_name": "瑞幸咖啡",
        "category": "咖啡茶饮",
        "product_name": "瑞幸10次卡",
        "original_price": 150.0,
        "activity_price": 49.9,
        "discount_description": "49.9元10杯卡，相当于5元/杯",
        "usage_conditions": "京东下单，30天有效",
        "valid_to": _days(60),
        "source_url": "https://m.jd.com/search?keyword=瑞幸咖啡",
        "app_url": "openApp.jdMobile://virtual?params={%22category%22:%22jump%22,%22des%22:%22m%22,%22url%22:%22https://m.jd.com/search?keyword=瑞幸咖啡%22}",
        "source_type": "manual",
    },
    {
        "id": "act_elm_luckin_12",
        "title": "瑞幸咖啡饿了么 12元单杯",
        "platform": "饿了么",
        "merchant_name": "瑞幸咖啡",
        "category": "咖啡茶饮",
        "product_name": "瑞幸单杯外卖券",
        "original_price": 25.0,
        "activity_price": 12.0,
        "discount_description": "12元单杯，送外卖到家",
        "usage_conditions": "饿了么App下单，外卖配送",
        "valid_to": _days(10),
        "source_url": "https://h5.ele.me/search?keyword=瑞幸咖啡",
        "app_url": "eleme://search?keyword=瑞幸咖啡",
        "source_type": "manual",
    },
    {
        "id": "act_tb_luckin_88",
        "title": "瑞幸咖啡淘宝 88元月卡",
        "platform": "淘宝",
        "merchant_name": "瑞幸咖啡",
        "category": "咖啡茶饮",
        "product_name": "瑞幸月卡30杯",
        "original_price": 300.0,
        "activity_price": 88.0,
        "discount_description": "88元月卡，30杯≈2.9元/杯",
        "usage_conditions": "淘宝下单，30天有效",
        "valid_to": _days(30),
        "source_url": "https://m.taobao.com/search?q=瑞幸咖啡月卡",
        "app_url": "taobao://m.taobao.com/search?q=瑞幸咖啡月卡",
        "source_type": "manual",
    },

    # ===================================================
    # 星巴克 (5 platforms)
    # ===================================================
    {
        "id": "act_dy_starbucks_bogo",
        "title": "星巴克抖音券 周三买一赠一",
        "platform": "抖音",
        "merchant_name": "星巴克",
        "category": "咖啡茶饮",
        "product_name": "星巴克指定饮品买一赠一",
        "original_price": 38.0,
        "activity_price": 19.0,
        "discount_description": "周三买一赠一，相当于半价",
        "usage_conditions": "仅限周三，指定饮品",
        "valid_to": _days(30),
        "source_url": "https://www.douyin.com/search/%E6%98%9F%E5%B7%B4%E5%85%8B%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E6%98%9F%E5%B7%B4%E5%85%8B%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_mt_starbucks_39",
        "title": "星巴克美团券 39元2杯任选",
        "platform": "美团",
        "merchant_name": "星巴克",
        "category": "咖啡茶饮",
        "product_name": "星巴克2杯任选券",
        "original_price": 76.0,
        "activity_price": 39.0,
        "discount_description": "39元2杯任选，省37元",
        "usage_conditions": "美团App下单，到店自取",
        "valid_to": _days(14),
        "source_url": "https://i.meituan.com/s/%E6%98%9F%E5%B7%B4%E5%85%8B/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=星巴克",
        "source_type": "manual",
    },
    {
        "id": "act_al_starbucks_25",
        "title": "星巴克支付宝 25元单杯",
        "platform": "支付宝",
        "merchant_name": "星巴克",
        "category": "咖啡茶饮",
        "product_name": "星巴克单杯券",
        "original_price": 38.0,
        "activity_price": 25.0,
        "discount_description": "25元单杯，省13元",
        "usage_conditions": "支付宝星巴克小程序",
        "valid_to": _days(14),
        "source_url": "https://render.alipay.com/p/s/starbucks",
        "app_url": "alipays://platformapi/startapp?appId=20001&page=pages/home/index&query=merchant%3Dstarbucks",
        "source_type": "manual",
    },
    {
        "id": "act_elm_starbucks_42",
        "title": "星巴克饿了么 42元双杯外卖",
        "platform": "饿了么",
        "merchant_name": "星巴克",
        "category": "咖啡茶饮",
        "product_name": "星巴克双杯外卖券",
        "original_price": 76.0,
        "activity_price": 42.0,
        "discount_description": "42元双杯外卖到家",
        "usage_conditions": "饿了么下单，外卖配送",
        "valid_to": _days(7),
        "source_url": "https://h5.ele.me/search?keyword=星巴克",
        "app_url": "eleme://search?keyword=星巴克",
        "source_type": "manual",
    },
    # 第五个：滴滴代下单（无星巴克优惠但可作为跨平台对比展示）
    {
        "id": "act_didi_starbucks",
        "title": "星巴克滴滴专车 到店立减5元",
        "platform": "滴滴",
        "merchant_name": "星巴克",
        "category": "咖啡茶饮",
        "product_name": "滴滴到星巴克立减券",
        "original_price": 5.0,
        "activity_price": 0.0,
        "discount_description": "滴滴App打车去星巴克，到店消费立减5元",
        "usage_conditions": "滴滴App打车到星巴克门店",
        "valid_to": _days(15),
        "source_url": "https://www.didiglobal.com/",
        "app_url": "diditaxi://",
        "source_type": "manual",
    },

    # ===================================================
    # 麦当劳 (3 platforms)
    # ===================================================
    {
        "id": "act_mt_mcd_25",
        "title": "麦当劳美团券 25元单人套餐",
        "platform": "美团",
        "merchant_name": "麦当劳",
        "category": "餐饮美食",
        "product_name": "麦当劳单人套餐",
        "original_price": 39.0,
        "activity_price": 25.0,
        "discount_description": "25元单人套餐，省14元",
        "usage_conditions": "美团App下单",
        "valid_to": _days(14),
        "source_url": "https://i.meituan.com/s/%E9%BA%A6%E5%BD%93%E5%8A%B3/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=麦当劳",
        "source_type": "manual",
    },
    {
        "id": "act_dy_mcd_29",
        "title": "麦当劳抖音券 29元双人套餐",
        "platform": "抖音",
        "merchant_name": "麦当劳",
        "category": "餐饮美食",
        "product_name": "麦当劳双人套餐",
        "original_price": 59.0,
        "activity_price": 29.0,
        "discount_description": "29元双人套餐，省30元",
        "usage_conditions": "抖音App下单，到店自取",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/%E9%BA%A6%E5%BD%93%E5%8A%B3%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E9%BA%A6%E5%BD%93%E5%8A%B3%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_al_mcd_39",
        "title": "麦当劳支付宝 39元全家桶",
        "platform": "支付宝",
        "merchant_name": "麦当劳",
        "category": "餐饮美食",
        "product_name": "麦当劳全家桶",
        "original_price": 79.0,
        "activity_price": 39.0,
        "discount_description": "39元全家桶，省40元",
        "usage_conditions": "支付宝麦当劳小程序",
        "valid_to": _days(14),
        "source_url": "https://render.alipay.com/p/s/mcdonalds",
        "app_url": "alipays://platformapi/startapp?appId=20001&page=pages/home/index&query=merchant%3Dmcdonalds",
        "source_type": "manual",
    },

    # ===================================================
    # 肯德基 (3 platforms)
    # ===================================================
    {
        "id": "act_mt_kfc_22",
        "title": "肯德基美团券 22元单人套餐",
        "platform": "美团",
        "merchant_name": "肯德基",
        "category": "餐饮美食",
        "product_name": "肯德基单人套餐",
        "original_price": 35.0,
        "activity_price": 22.0,
        "discount_description": "22元单人套餐，省13元",
        "usage_conditions": "美团App下单",
        "valid_to": _days(10),
        "source_url": "https://i.meituan.com/s/%E8%82%AF%E5%BE%B7%E5%9F%BA/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=肯德基",
        "source_type": "manual",
    },
    {
        "id": "act_dy_kfc_19",
        "title": "肯德基抖音券 19.9元疯狂星期四",
        "platform": "抖音",
        "merchant_name": "肯德基",
        "category": "餐饮美食",
        "product_name": "肯德基疯狂星期四套餐",
        "original_price": 49.9,
        "activity_price": 19.9,
        "discount_description": "19.9元疯狂星期四，省30元",
        "usage_conditions": "仅限周四，抖音App下单",
        "valid_to": _days(30),
        "source_url": "https://www.douyin.com/search/%E8%82%AF%E5%BE%B7%E5%9F%BA%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E8%82%AF%E5%BE%B7%E5%9F%BA%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_elm_kfc_29",
        "title": "肯德基饿了么 29元双人餐",
        "platform": "饿了么",
        "merchant_name": "肯德基",
        "category": "餐饮美食",
        "product_name": "肯德基双人外卖套餐",
        "original_price": 59.0,
        "activity_price": 29.0,
        "discount_description": "29元双人外卖套餐",
        "usage_conditions": "饿了么下单，外卖配送",
        "valid_to": _days(7),
        "source_url": "https://h5.ele.me/search?keyword=肯德基",
        "app_url": "eleme://search?keyword=肯德基",
        "source_type": "manual",
    },

    # ===================================================
    # 喜茶 (3 platforms)
    # ===================================================
    {
        "id": "act_mt_heytea_25",
        "title": "喜茶美团券 25元2杯",
        "platform": "美团",
        "merchant_name": "喜茶",
        "category": "咖啡茶饮",
        "product_name": "喜茶2杯任选券",
        "original_price": 60.0,
        "activity_price": 25.0,
        "discount_description": "25元2杯，相当于12.5元/杯",
        "usage_conditions": "美团App下单，到店自取",
        "valid_to": _days(7),
        "source_url": "https://i.meituan.com/s/%E5%96%9C%E8%8C%B6/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=喜茶",
        "source_type": "manual",
    },
    {
        "id": "act_dy_heytea_19",
        "title": "喜茶抖音券 19.9元任选1杯",
        "platform": "抖音",
        "merchant_name": "喜茶",
        "category": "咖啡茶饮",
        "product_name": "喜茶单杯券",
        "original_price": 30.0,
        "activity_price": 19.9,
        "discount_description": "19.9元任选1杯，省10元",
        "usage_conditions": "抖音App下单",
        "valid_to": _days(5),
        "source_url": "https://www.douyin.com/search/%E5%96%9C%E8%8C%B6%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E5%96%9C%E8%8C%B6%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_al_heytea_18",
        "title": "喜茶支付宝 18元单杯",
        "platform": "支付宝",
        "merchant_name": "喜茶",
        "category": "咖啡茶饮",
        "product_name": "喜茶单杯券",
        "original_price": 30.0,
        "activity_price": 18.0,
        "discount_description": "18元单杯，支付宝专享",
        "usage_conditions": "支付宝喜茶小程序",
        "valid_to": _days(14),
        "source_url": "https://render.alipay.com/p/s/heytea",
        "app_url": "alipays://platformapi/startapp?appId=20001&page=pages/home/index&query=merchant%3Dheytea",
        "source_type": "manual",
    },

    # ===================================================
    # 奈雪的茶 (2 platforms)
    # ===================================================
    {
        "id": "act_mt_nayuki_20",
        "title": "奈雪的茶美团券 20元2杯",
        "platform": "美团",
        "merchant_name": "奈雪的茶",
        "category": "咖啡茶饮",
        "product_name": "奈雪2杯套餐",
        "original_price": 56.0,
        "activity_price": 20.0,
        "discount_description": "20元2杯，相当于10元/杯",
        "usage_conditions": "美团App下单",
        "valid_to": _days(7),
        "source_url": "https://i.meituan.com/s/%E5%A5%88%E9%9B%AA%E7%9A%84%E8%8C%B6/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=奈雪的茶",
        "source_type": "manual",
    },
    {
        "id": "act_dy_nayuki_15",
        "title": "奈雪的茶抖音券 15.9元单杯",
        "platform": "抖音",
        "merchant_name": "奈雪的茶",
        "category": "咖啡茶饮",
        "product_name": "奈雪单杯券",
        "original_price": 28.0,
        "activity_price": 15.9,
        "discount_description": "15.9元单杯，省12元",
        "usage_conditions": "抖音App下单",
        "valid_to": _days(5),
        "source_url": "https://www.douyin.com/search/%E5%A5%88%E9%9B%AA%E7%9A%84%E8%8C%B6%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E5%A5%88%E9%9B%AA%E7%9A%84%E8%8C%B6%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },

    # ===================================================
    # 海底捞 (3 platforms)
    # ===================================================
    {
        "id": "act_mt_haidilao_99",
        "title": "海底捞美团券 99元双人套餐",
        "platform": "美团",
        "merchant_name": "海底捞",
        "category": "餐饮美食",
        "product_name": "海底捞双人套餐",
        "original_price": 180.0,
        "activity_price": 99.0,
        "discount_description": "99元双人套餐，省81元",
        "usage_conditions": "美团App下单，到店核销",
        "valid_to": _days(14),
        "source_url": "https://i.meituan.com/s/%E6%B5%B7%E5%BA%95%E6%8D%9E/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=海底捞",
        "source_type": "manual",
    },
    {
        "id": "act_dy_haidilao_88",
        "title": "海底捞抖音券 88元工作日午市",
        "platform": "抖音",
        "merchant_name": "海底捞",
        "category": "餐饮美食",
        "product_name": "海底捞工作日午市套餐",
        "original_price": 150.0,
        "activity_price": 88.0,
        "discount_description": "88元工作日午市，省62元",
        "usage_conditions": "工作日午市，抖音App下单",
        "valid_to": _days(30),
        "source_url": "https://www.douyin.com/search/%E6%B5%B7%E5%BA%95%E6%8D%9E%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E6%B5%B7%E5%BA%95%E6%8D%9E%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_al_haidilao_108",
        "title": "海底捞支付宝 108元双人套餐",
        "platform": "支付宝",
        "merchant_name": "海底捞",
        "category": "餐饮美食",
        "product_name": "海底捞双人套餐",
        "original_price": 180.0,
        "activity_price": 108.0,
        "discount_description": "108元双人套餐，省72元",
        "usage_conditions": "支付宝海底捞小程序",
        "valid_to": _days(14),
        "source_url": "https://render.alipay.com/p/s/haidilao",
        "app_url": "alipays://platformapi/startapp?appId=20001&page=pages/home/index&query=merchant%3Dhaidilao",
        "source_type": "manual",
    },

    # ===================================================
    # 必胜客 (2 platforms)
    # ===================================================
    {
        "id": "act_mt_pizzahut_59",
        "title": "必胜客美团券 59元双人披萨套餐",
        "platform": "美团",
        "merchant_name": "必胜客",
        "category": "餐饮美食",
        "product_name": "必胜客双人披萨套餐",
        "original_price": 119.0,
        "activity_price": 59.0,
        "discount_description": "59元双人披萨套餐，半价",
        "usage_conditions": "美团App下单",
        "valid_to": _days(10),
        "source_url": "https://i.meituan.com/s/%E5%BF%85%E8%83%9C%E5%AE%A2/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=必胜客",
        "source_type": "manual",
    },
    {
        "id": "act_dy_pizzahut_49",
        "title": "必胜客抖音券 49元单人套餐",
        "platform": "抖音",
        "merchant_name": "必胜客",
        "category": "餐饮美食",
        "product_name": "必胜客单人披萨套餐",
        "original_price": 89.0,
        "activity_price": 49.0,
        "discount_description": "49元单人套餐，省40元",
        "usage_conditions": "抖音App下单",
        "valid_to": _days(10),
        "source_url": "https://www.douyin.com/search/%E5%BF%85%E8%83%9C%E5%AE%A2%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E5%BF%85%E8%83%9C%E5%AE%A2%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },

    # ===================================================
    # 蜜雪冰城 (2 platforms)
    # ===================================================
    {
        "id": "act_mt_milktea_9",
        "title": "蜜雪冰城美团券 9.9元3杯",
        "platform": "美团",
        "merchant_name": "蜜雪冰城",
        "category": "咖啡茶饮",
        "product_name": "蜜雪冰城3杯套餐",
        "original_price": 18.0,
        "activity_price": 9.9,
        "discount_description": "9.9元3杯，相当于3.3元/杯",
        "usage_conditions": "美团App下单",
        "valid_to": _days(7),
        "source_url": "https://i.meituan.com/s/%E8%9C%9C%E9%9B%AA%E5%86%B0%E5%9F%8E/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=蜜雪冰城",
        "source_type": "manual",
    },
    {
        "id": "act_dy_milktea_6",
        "title": "蜜雪冰城抖音券 6.6元2杯",
        "platform": "抖音",
        "merchant_name": "蜜雪冰城",
        "category": "咖啡茶饮",
        "product_name": "蜜雪冰城2杯券",
        "original_price": 12.0,
        "activity_price": 6.6,
        "discount_description": "6.6元2杯，相当于3.3元/杯",
        "usage_conditions": "抖音App下单",
        "valid_to": _days(5),
        "source_url": "https://www.douyin.com/search/%E8%9C%9C%E9%9B%AA%E5%86%B0%E5%9F%8E%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E8%9C%9C%E9%9B%AA%E5%86%B0%E5%9F%8E%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },

    # ===================================================
    # 汉堡王 (2 platforms)
    # ===================================================
    {
        "id": "act_mt_burger_35",
        "title": "汉堡王美团券 35元双人套餐",
        "platform": "美团",
        "merchant_name": "汉堡王",
        "category": "餐饮美食",
        "product_name": "汉堡王双人套餐",
        "original_price": 69.0,
        "activity_price": 35.0,
        "discount_description": "35元双人套餐，省34元",
        "usage_conditions": "美团App下单",
        "valid_to": _days(10),
        "source_url": "https://i.meituan.com/s/%E6%B1%89%E5%A0%A1%E7%8E%8B/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=汉堡王",
        "source_type": "manual",
    },
    {
        "id": "act_dy_burger_28",
        "title": "汉堡王抖音券 28元皇堡套餐",
        "platform": "抖音",
        "merchant_name": "汉堡王",
        "category": "餐饮美食",
        "product_name": "汉堡王皇堡套餐",
        "original_price": 49.0,
        "activity_price": 28.0,
        "discount_description": "28元皇堡单人套餐",
        "usage_conditions": "抖音App下单",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/%E6%B1%89%E5%A0%A1%E7%8E%8B%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E6%B1%89%E5%A0%A1%E7%8E%8B%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },

    # ===================================================
    # 库迪咖啡 (2 platforms)
    # ===================================================
    {
        "id": "act_dy_cotti_7",
        "title": "库迪咖啡抖音券 7.7元单杯",
        "platform": "抖音",
        "merchant_name": "库迪咖啡",
        "category": "咖啡茶饮",
        "product_name": "库迪咖啡单杯券",
        "original_price": 18.0,
        "activity_price": 7.7,
        "discount_description": "7.7元单杯，省10.3元",
        "usage_conditions": "抖音App下单",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/%E5%BA%93%E8%BF%AA%E5%92%96%E5%95%A1%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E5%BA%93%E8%BF%AA%E5%92%96%E5%95%A1%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_mt_cotti_12",
        "title": "库迪咖啡美团券 12元2杯",
        "platform": "美团",
        "merchant_name": "库迪咖啡",
        "category": "咖啡茶饮",
        "product_name": "库迪咖啡双杯券",
        "original_price": 36.0,
        "activity_price": 12.0,
        "discount_description": "12元2杯，相当于6元/杯",
        "usage_conditions": "美团App下单",
        "valid_to": _days(10),
        "source_url": "https://i.meituan.com/s/%E5%BA%93%E8%BF%AA%E5%92%96%E5%95%A1/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=库迪咖啡",
        "source_type": "manual",
    },

    # ===================================================
    # 霸王茶姬 (2 platforms)
    # ===================================================
    {
        "id": "act_dy_bawang_15",
        "title": "霸王茶姬抖音券 15元单杯",
        "platform": "抖音",
        "merchant_name": "霸王茶姬",
        "category": "咖啡茶饮",
        "product_name": "霸王茶姬单杯券",
        "original_price": 25.0,
        "activity_price": 15.0,
        "discount_description": "15元单杯，省10元",
        "usage_conditions": "抖音App下单",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/%E9%9C%B8%E7%8E%8B%E8%8C%B6%E5%A7%AC%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E9%9C%B8%E7%8E%8B%E8%8C%B6%E5%A7%AC%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_mt_bawang_28",
        "title": "霸王茶姬美团券 28元2杯",
        "platform": "美团",
        "merchant_name": "霸王茶姬",
        "category": "咖啡茶饮",
        "product_name": "霸王茶姬双杯券",
        "original_price": 50.0,
        "activity_price": 28.0,
        "discount_description": "28元2杯，相当于14元/杯",
        "usage_conditions": "美团App下单",
        "valid_to": _days(7),
        "source_url": "https://i.meituan.com/s/%E9%9C%B8%E7%8E%8B%E8%8C%B6%E5%A7%AC/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=霸王茶姬",
        "source_type": "manual",
    },

    # ===================================================
    # 茶百道 (2 platforms)
    # ===================================================
    {
        "id": "act_dy_chabaidao_8",
        "title": "茶百道抖音券 8.8元单杯",
        "platform": "抖音",
        "merchant_name": "茶百道",
        "category": "咖啡茶饮",
        "product_name": "茶百道单杯券",
        "original_price": 18.0,
        "activity_price": 8.8,
        "discount_description": "8.8元单杯，省9.2元",
        "usage_conditions": "抖音App下单",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/%E8%8C%B6%E7%99%BE%E9%81%93%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E8%8C%B6%E7%99%BE%E9%81%93%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_mt_chabaidao_15",
        "title": "茶百道美团券 15元2杯",
        "platform": "美团",
        "merchant_name": "茶百道",
        "category": "咖啡茶饮",
        "product_name": "茶百道双杯券",
        "original_price": 36.0,
        "activity_price": 15.0,
        "discount_description": "15元2杯，相当于7.5元/杯",
        "usage_conditions": "美团App下单",
        "valid_to": _days(10),
        "source_url": "https://i.meituan.com/s/%E8%8C%B6%E7%99%BE%E9%81%93/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=茶百道",
        "source_type": "manual",
    },

    # ===================================================
    # 塔斯汀 (2 platforms)
    # ===================================================
    {
        "id": "act_dy_tastin_15",
        "title": "塔斯汀抖音券 15元汉堡套餐",
        "platform": "抖音",
        "merchant_name": "塔斯汀",
        "category": "餐饮美食",
        "product_name": "塔斯汀中国汉堡套餐",
        "original_price": 29.0,
        "activity_price": 15.0,
        "discount_description": "15元汉堡套餐，省14元",
        "usage_conditions": "抖音App下单",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/%E5%A1%94%E6%96%AF%E6%B1%80%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E5%A1%94%E6%96%AF%E6%B1%80%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_mt_tastin_22",
        "title": "塔斯汀美团券 22元双人套餐",
        "platform": "美团",
        "merchant_name": "塔斯汀",
        "category": "餐饮美食",
        "product_name": "塔斯汀双人汉堡餐",
        "original_price": 45.0,
        "activity_price": 22.0,
        "discount_description": "22元双人套餐，省23元",
        "usage_conditions": "美团App下单",
        "valid_to": _days(10),
        "source_url": "https://i.meituan.com/s/%E5%A1%94%E6%96%AF%E6%B1%80/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=塔斯汀",
        "source_type": "manual",
    },

    # ===================================================
    # 华莱士 (2 platforms)
    # ===================================================
    {
        "id": "act_dy_wallace_12",
        "title": "华莱士抖音券 12元炸鸡套餐",
        "platform": "抖音",
        "merchant_name": "华莱士",
        "category": "餐饮美食",
        "product_name": "华莱士炸鸡套餐",
        "original_price": 25.0,
        "activity_price": 12.0,
        "discount_description": "12元炸鸡套餐，省13元",
        "usage_conditions": "抖音App下单",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/%E5%8D%8E%E8%8E%B1%E5%A3%AB%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E5%8D%8E%E8%8E%B1%E5%A3%AB%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_mt_wallace_35",
        "title": "华莱士美团券 35元全家桶",
        "platform": "美团",
        "merchant_name": "华莱士",
        "category": "餐饮美食",
        "product_name": "华莱士全家桶",
        "original_price": 69.0,
        "activity_price": 35.0,
        "discount_description": "35元全家桶，省34元",
        "usage_conditions": "美团App下单",
        "valid_to": _days(10),
        "source_url": "https://i.meituan.com/s/%E5%8D%8E%E8%8E%B1%E5%A3%AB/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=华莱士",
        "source_type": "manual",
    },

    # ===================================================
    # 达美乐 (2 platforms)
    # ===================================================
    {
        "id": "act_dy_domino_39",
        "title": "达美乐抖音券 39元9寸披萨",
        "platform": "抖音",
        "merchant_name": "达美乐",
        "category": "餐饮美食",
        "product_name": "达美乐9寸披萨",
        "original_price": 69.0,
        "activity_price": 39.0,
        "discount_description": "39元9寸披萨，省30元",
        "usage_conditions": "抖音App下单",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/%E8%BE%BE%E7%BE%8E%E4%B9%90%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E8%BE%BE%E7%BE%8E%E4%B9%90%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_mt_domino_28",
        "title": "达美乐美团券 28元单人披萨套餐",
        "platform": "美团",
        "merchant_name": "达美乐",
        "category": "餐饮美食",
        "product_name": "达美乐单人套餐",
        "original_price": 55.0,
        "activity_price": 28.0,
        "discount_description": "28元单人套餐，省27元",
        "usage_conditions": "美团App下单",
        "valid_to": _days(10),
        "source_url": "https://i.meituan.com/s/%E8%BE%BE%E7%BE%8E%E4%B9%90/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=达美乐",
        "source_type": "manual",
    },

    # ===================================================
    # Manner咖啡 (2 platforms)
    # ===================================================
    {
        "id": "act_dy_manner_15",
        "title": "Manner抖音券 15元单杯",
        "platform": "抖音",
        "merchant_name": "Manner咖啡",
        "category": "咖啡茶饮",
        "product_name": "Manner单杯券",
        "original_price": 20.0,
        "activity_price": 15.0,
        "discount_description": "15元单杯，自带杯再减5元",
        "usage_conditions": "抖音App下单",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/Manner%E5%92%96%E5%95%A1%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/Manner%E5%92%96%E5%95%A1%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_mt_manner_25",
        "title": "Manner美团券 25元2杯",
        "platform": "美团",
        "merchant_name": "Manner咖啡",
        "category": "咖啡茶饮",
        "product_name": "Manner双杯券",
        "original_price": 40.0,
        "activity_price": 25.0,
        "discount_description": "25元2杯，相当于12.5元/杯",
        "usage_conditions": "美团App下单",
        "valid_to": _days(2),
        "source_url": "https://i.meituan.com/s/Manner/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=Manner",
        "source_type": "manual",
    },

    # ===================================================
    # 虎头局 (1)
    # ===================================================
    {
        "id": "act_mt_hutouju_18",
        "title": "虎头局美团券 18元点心套餐",
        "platform": "美团",
        "merchant_name": "虎头局",
        "category": "餐饮美食",
        "product_name": "虎头局点心任选套餐",
        "original_price": 35.0,
        "activity_price": 18.0,
        "discount_description": "18元点心套餐，省17元",
        "usage_conditions": "美团App下单",
        "valid_to": _days(7),
        "source_url": "https://i.meituan.com/s/%E8%99%8E%E5%A4%B4%E5%B1%80/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=虎头局",
        "source_type": "manual",
    },

    # ===================================================
    # 西贝莜面村 (2 platforms)
    # ===================================================
    {
        "id": "act_dy_xibei_68",
        "title": "西贝抖音券 68元双人套餐",
        "platform": "抖音",
        "merchant_name": "西贝莜面村",
        "category": "餐饮美食",
        "product_name": "西贝双人套餐",
        "original_price": 128.0,
        "activity_price": 68.0,
        "discount_description": "68元双人套餐，省60元",
        "usage_conditions": "抖音App下单",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/%E8%A5%BF%E8%B4%9D%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E8%A5%BF%E8%B4%9D%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_mt_xibei_88",
        "title": "西贝美团券 88元家庭套餐",
        "platform": "美团",
        "merchant_name": "西贝莜面村",
        "category": "餐饮美食",
        "product_name": "西贝3-4人家庭套餐",
        "original_price": 188.0,
        "activity_price": 88.0,
        "discount_description": "88元家庭套餐，省100元",
        "usage_conditions": "美团App下单",
        "valid_to": _days(14),
        "source_url": "https://i.meituan.com/s/%E8%A5%BF%E8%B4%9D/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=西贝",
        "source_type": "manual",
    },

    # ===================================================
    # 全聚德 (1)
    # ===================================================
    {
        "id": "act_mt_quanjude_198",
        "title": "全聚德美团券 198元烤鸭双人套餐",
        "platform": "美团",
        "merchant_name": "全聚德",
        "category": "餐饮美食",
        "product_name": "全聚德烤鸭双人套餐",
        "original_price": 398.0,
        "activity_price": 198.0,
        "discount_description": "198元烤鸭双人套餐，省200元",
        "usage_conditions": "美团App下单，提前预约",
        "valid_to": _days(30),
        "source_url": "https://i.meituan.com/s/%E5%85%A8%E8%81%9A%E5%BE%B7/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=全聚德",
        "source_type": "manual",
    },

    # ===================================================
    # 超市便利 (3)
    # ===================================================
    {
        "id": "act_mt_walmart_15",
        "title": "沃尔玛美团券 满100减15",
        "platform": "美团",
        "merchant_name": "沃尔玛",
        "category": "超市便利",
        "product_name": "沃尔玛超市满减券",
        "original_price": 100.0,
        "activity_price": 85.0,
        "discount_description": "满100减15，相当于85折",
        "usage_conditions": "美团闪购下单",
        "valid_to": _days(14),
        "source_url": "https://i.meituan.com/s/%E6%B2%83%E5%B0%94%E7%8E%9B/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=沃尔玛",
        "source_type": "manual",
    },
    {
        "id": "act_elm_freshhema_20",
        "title": "盒马饿了么 鲜生满88减20",
        "platform": "饿了么",
        "merchant_name": "盒马鲜生",
        "category": "超市便利",
        "product_name": "盒马鲜生满减券",
        "original_price": 88.0,
        "activity_price": 68.0,
        "discount_description": "满88减20，新鲜直达",
        "usage_conditions": "饿了么盒马下单",
        "valid_to": _days(7),
        "source_url": "https://h5.ele.me/search?keyword=盒马鲜生",
        "app_url": "eleme://search?keyword=盒马鲜生",
        "source_type": "manual",
    },
    {
        "id": "act_jd_supermarket_30",
        "title": "京东超市 满199减30",
        "platform": "京东",
        "merchant_name": "京东超市",
        "category": "超市便利",
        "product_name": "京东超市满减券",
        "original_price": 199.0,
        "activity_price": 169.0,
        "discount_description": "满199减30，囤货好时机",
        "usage_conditions": "京东App下单",
        "valid_to": _days(14),
        "source_url": "https://m.jd.com/search?keyword=京东超市满减",
        "app_url": "openApp.jdMobile://virtual?params={%22category%22:%22jump%22,%22des%22:%22m%22,%22url%22:%22https://m.jd.com/search?keyword=京东超市满减%22}",
        "source_type": "manual",
    },

    # ===================================================
    # 滴滴出行 (2)
    # ===================================================
    {
        "id": "act_didi_kuaiche_5",
        "title": "滴滴快车 工作日9折券",
        "platform": "滴滴",
        "merchant_name": "滴滴出行",
        "category": "出行旅游",
        "product_name": "滴滴快车折扣券",
        "original_price": 0.0,
        "activity_price": 0.0,
        "discount_description": "工作日快车9折，最高减5元",
        "usage_conditions": "滴滴App/小程序打车",
        "valid_to": _days(7),
        "source_url": "https://www.didiglobal.com/",
        "app_url": "diditaxi://",
        "source_type": "manual",
    },
    {
        "id": "act_al_didi_8",
        "title": "滴滴支付宝 88折券",
        "platform": "支付宝",
        "merchant_name": "滴滴出行",
        "category": "出行旅游",
        "product_name": "滴滴打车券",
        "original_price": 0.0,
        "activity_price": 0.0,
        "discount_description": "支付宝滴滴88折，最高减8元",
        "usage_conditions": "支付宝滴滴小程序",
        "valid_to": _days(10),
        "source_url": "https://render.alipay.com/p/s/didi",
        "app_url": "alipays://platformapi/startapp?appId=20000778&sourceId=ccreward&page=pages/index/index",
        "source_type": "manual",
    },

    # ===================================================
    # === 新增20+条活动 ===
    # 茶颜悦色 (2)
    # ===================================================
    {
        "id": "act_dy_modern_tea_16",
        "title": "茶颜悦色抖音券 16元单杯",
        "platform": "抖音",
        "merchant_name": "茶颜悦色",
        "category": "咖啡茶饮",
        "product_name": "茶颜悦色单杯券",
        "original_price": 22.0,
        "activity_price": 16.0,
        "discount_description": "16元单杯，省6元",
        "usage_conditions": "抖音App下单，长沙/武汉/南京门店",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/%E8%8C%B6%E9%A2%9C%E6%82%A6%E8%89%B2%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E8%8C%B6%E9%A2%9C%E6%82%A6%E8%89%B2%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_mt_modern_tea_28",
        "title": "茶颜悦色美团券 28元2杯",
        "platform": "美团",
        "merchant_name": "茶颜悦色",
        "category": "咖啡茶饮",
        "product_name": "茶颜悦色双杯券",
        "original_price": 44.0,
        "activity_price": 28.0,
        "discount_description": "28元2杯，相当于14元/杯",
        "usage_conditions": "美团App下单",
        "valid_to": _days(7),
        "source_url": "https://i.meituan.com/s/%E8%8C%B6%E9%A2%9C%E6%82%A6%E8%89%B2/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=茶颜悦色",
        "source_type": "manual",
    },

    # ===================================================
    # 太二酸菜鱼 (2)
    # ===================================================
    {
        "id": "act_dy_taier_128",
        "title": "太二酸菜鱼抖音券 128元双人套餐",
        "platform": "抖音",
        "merchant_name": "太二酸菜鱼",
        "category": "餐饮美食",
        "product_name": "太二双人套餐",
        "original_price": 198.0,
        "activity_price": 128.0,
        "discount_description": "128元双人套餐，省70元",
        "usage_conditions": "抖音App下单，到店核销",
        "valid_to": _days(14),
        "source_url": "https://www.douyin.com/search/%E5%A4%AA%E4%BA%8C%E9%85%B8%E8%8F%9C%E9%B1%BC%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E5%A4%AA%E4%BA%8C%E9%85%B8%E8%8F%9C%E9%B1%BC%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_mt_taier_138",
        "title": "太二酸菜鱼美团券 138元2-3人套餐",
        "platform": "美团",
        "merchant_name": "太二酸菜鱼",
        "category": "餐饮美食",
        "product_name": "太二2-3人套餐",
        "original_price": 228.0,
        "activity_price": 138.0,
        "discount_description": "138元2-3人套餐，省90元",
        "usage_conditions": "美团App下单，到店核销",
        "valid_to": _days(14),
        "source_url": "https://i.meituan.com/s/%E5%A4%AA%E4%BA%8C/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=太二",
        "source_type": "manual",
    },

    # ===================================================
    # 呷哺呷哺 (2)
    # ===================================================
    {
        "id": "act_mt_xiabu_69",
        "title": "呷哺呷哺美团券 69元双人火锅",
        "platform": "美团",
        "merchant_name": "呷哺呷哺",
        "category": "餐饮美食",
        "product_name": "呷哺双人火锅套餐",
        "original_price": 128.0,
        "activity_price": 69.0,
        "discount_description": "69元双人火锅，省59元",
        "usage_conditions": "美团App下单",
        "valid_to": _days(10),
        "source_url": "https://i.meituan.com/s/%E5%91%B7%E5%93%BA%E5%91%B7%E5%93%BA/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=呷哺呷哺",
        "source_type": "manual",
    },
    {
        "id": "act_dy_xiabu_59",
        "title": "呷哺呷哺抖音券 59元单人火锅",
        "platform": "抖音",
        "merchant_name": "呷哺呷哺",
        "category": "餐饮美食",
        "product_name": "呷哺单人火锅套餐",
        "original_price": 89.0,
        "activity_price": 59.0,
        "discount_description": "59元单人火锅，省30元",
        "usage_conditions": "抖音App下单",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/%E5%91%B7%E5%93%BA%E5%91%B7%E5%93%BA%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E5%91%B7%E5%93%BA%E5%91%B7%E5%93%BA%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },

    # ===================================================
    # 杨国福麻辣烫 (2)
    # ===================================================
    {
        "id": "act_dy_ygf_18",
        "title": "杨国福抖音券 18.8元单人套餐",
        "platform": "抖音",
        "merchant_name": "杨国福麻辣烫",
        "category": "餐饮美食",
        "product_name": "杨国福单人套餐",
        "original_price": 29.0,
        "activity_price": 18.8,
        "discount_description": "18.8元单人套餐，省10.2元",
        "usage_conditions": "抖音App下单",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/%E6%9D%A8%E5%9B%BD%E7%A6%8F%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E6%9D%A8%E5%9B%BD%E7%A6%8F%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_mt_ygf_25",
        "title": "杨国福美团券 25元2人分享餐",
        "platform": "美团",
        "merchant_name": "杨国福麻辣烫",
        "category": "餐饮美食",
        "product_name": "杨国福双人套餐",
        "original_price": 45.0,
        "activity_price": 25.0,
        "discount_description": "25元双人分享，省20元",
        "usage_conditions": "美团App下单",
        "valid_to": _days(10),
        "source_url": "https://i.meituan.com/s/%E6%9D%A8%E5%9B%BD%E7%A6%8F/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=杨国福",
        "source_type": "manual",
    },

    # ===================================================
    # 茉酸奶 (2)
    # ===================================================
    {
        "id": "act_dy_moreyogurt_15",
        "title": "茉酸奶抖音券 15.9元牛油果酸奶奶昔",
        "platform": "抖音",
        "merchant_name": "茉酸奶",
        "category": "咖啡茶饮",
        "product_name": "茉酸奶牛油果酸奶奶昔",
        "original_price": 26.0,
        "activity_price": 15.9,
        "discount_description": "15.9元招牌牛油果，省10元",
        "usage_conditions": "抖音App下单，到店自取",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/%E8%8C%89%E9%85%B8%E5%A5%B6%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E8%8C%89%E9%85%B8%E5%A5%B6%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_mt_moreyogurt_26",
        "title": "茉酸奶美团券 26元2杯",
        "platform": "美团",
        "merchant_name": "茉酸奶",
        "category": "咖啡茶饮",
        "product_name": "茉酸奶双杯券",
        "original_price": 52.0,
        "activity_price": 26.0,
        "discount_description": "26元2杯，相当于13元/杯",
        "usage_conditions": "美团App下单",
        "valid_to": _days(7),
        "source_url": "https://i.meituan.com/s/%E8%8C%89%E9%85%B8%E5%A5%B6/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=茉酸奶",
        "source_type": "manual",
    },

    # ===================================================
    # 便利蜂 (2)
    # ===================================================
    {
        "id": "act_mt_bianlifeng_15",
        "title": "便利蜂美团券 满20减5",
        "platform": "美团",
        "merchant_name": "便利蜂",
        "category": "超市便利",
        "product_name": "便利蜂满减券",
        "original_price": 20.0,
        "activity_price": 15.0,
        "discount_description": "满20减5，相当于75折",
        "usage_conditions": "美团外卖便利蜂下单",
        "valid_to": _days(14),
        "source_url": "https://i.meituan.com/s/%E4%BE%BF%E5%88%A9%E8%9C%82/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=便利蜂",
        "source_type": "manual",
    },
    {
        "id": "act_elm_bianlifeng_10",
        "title": "便利蜂饿了么 满18减3",
        "platform": "饿了么",
        "merchant_name": "便利蜂",
        "category": "超市便利",
        "product_name": "便利蜂满减券",
        "original_price": 18.0,
        "activity_price": 15.0,
        "discount_description": "满18减3，便利店即买即送",
        "usage_conditions": "饿了么下单",
        "valid_to": _days(7),
        "source_url": "https://h5.ele.me/search?keyword=便利蜂",
        "app_url": "eleme://search?keyword=便利蜂",
        "source_type": "manual",
    },

    # ===================================================
    # 屈臣氏 (2)
    # ===================================================
    {
        "id": "act_mt_watsons_15",
        "title": "屈臣氏美团券 满99减15",
        "platform": "美团",
        "merchant_name": "屈臣氏",
        "category": "超市便利",
        "product_name": "屈臣氏满减券",
        "original_price": 99.0,
        "activity_price": 84.0,
        "discount_description": "满99减15，日用品囤货",
        "usage_conditions": "美团闪购屈臣氏下单",
        "valid_to": _days(10),
        "source_url": "https://i.meituan.com/s/%E5%B1%88%E8%87%A3%E6%B0%8F/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=屈臣氏",
        "source_type": "manual",
    },
    {
        "id": "act_dy_watsons_88",
        "title": "屈臣氏抖音券 88元护肤套装",
        "platform": "抖音",
        "merchant_name": "屈臣氏",
        "category": "超市便利",
        "product_name": "屈臣氏护肤套装",
        "original_price": 188.0,
        "activity_price": 88.0,
        "discount_description": "88元护肤套装，省100元",
        "usage_conditions": "抖音App下单，到店自取",
        "valid_to": _days(5),
        "source_url": "https://www.douyin.com/search/%E5%B1%88%E8%87%A3%E6%B0%8F%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E5%B1%88%E8%87%A3%E6%B0%8F%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },

    # ===================================================
    # 大润发 (2)
    # ===================================================
    {
        "id": "act_mt_rtmart_20",
        "title": "大润发美团券 满129减20",
        "platform": "美团",
        "merchant_name": "大润发",
        "category": "超市便利",
        "product_name": "大润发超市满减券",
        "original_price": 129.0,
        "activity_price": 109.0,
        "discount_description": "满129减20，周末囤货",
        "usage_conditions": "美团外卖大润发下单",
        "valid_to": _days(7),
        "source_url": "https://i.meituan.com/s/%E5%A4%A7%E6%B6%A6%E5%8F%91/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=大润发",
        "source_type": "manual",
    },
    {
        "id": "act_elm_rtmart_15",
        "title": "大润发饿了么 满88减15",
        "platform": "饿了么",
        "merchant_name": "大润发",
        "category": "超市便利",
        "product_name": "大润发满减券",
        "original_price": 88.0,
        "activity_price": 73.0,
        "discount_description": "满88减15，新鲜蔬菜水果",
        "usage_conditions": "饿了么大润发下单",
        "valid_to": _days(7),
        "source_url": "https://h5.ele.me/search?keyword=大润发",
        "app_url": "eleme://search?keyword=大润发",
        "source_type": "manual",
    },

    # ===================================================
    # 高德打车 (2)
    # ===================================================
    {
        "id": "act_al_gaode_5",
        "title": "高德打车 支付宝88折券",
        "platform": "支付宝",
        "merchant_name": "高德打车",
        "category": "出行旅游",
        "product_name": "高德打车券",
        "original_price": 0.0,
        "activity_price": 0.0,
        "discount_description": "高德打车88折，最高减5元",
        "usage_conditions": "支付宝高德打车小程序",
        "valid_to": _days(7),
        "source_url": "https://render.alipay.com/p/s/amap",
        "app_url": "alipays://platformapi/startapp?appId=20000540&page=pages/index/index",
        "source_type": "manual",
    },
    {
        "id": "act_mt_gaode_3",
        "title": "高德打车 美团领券立减3元",
        "platform": "美团",
        "merchant_name": "高德打车",
        "category": "出行旅游",
        "product_name": "高德打车立减券",
        "original_price": 0.0,
        "activity_price": 0.0,
        "discount_description": "美团内领高德打车券，立减3元",
        "usage_conditions": "美团App领取，高德打车使用",
        "valid_to": _days(7),
        "source_url": "https://i.meituan.com/s/%E9%AB%98%E5%BE%B7%E6%89%93%E8%BD%A6/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=高德打车",
        "source_type": "manual",
    },

    # ===================================================
    # 携程 (2)
    # ===================================================
    {
        "id": "act_tb_xiecheng_199",
        "title": "携程淘宝 199元酒店券包",
        "platform": "淘宝",
        "merchant_name": "携程",
        "category": "出行旅游",
        "product_name": "携程酒店券包",
        "original_price": 499.0,
        "activity_price": 199.0,
        "discount_description": "199元酒店券包，含满减券+升房券",
        "usage_conditions": "淘宝下单，携程App使用",
        "valid_to": _days(30),
        "source_url": "https://m.taobao.com/search?q=携程酒店券",
        "app_url": "taobao://m.taobao.com/search?q=携程酒店券",
        "source_type": "manual",
    },
    {
        "id": "act_al_xiecheng_50",
        "title": "携程支付宝 满500减50",
        "platform": "支付宝",
        "merchant_name": "携程",
        "category": "出行旅游",
        "product_name": "携程满减券",
        "original_price": 500.0,
        "activity_price": 450.0,
        "discount_description": "预订酒店/机票满500减50",
        "usage_conditions": "支付宝携程小程序",
        "valid_to": _days(14),
        "source_url": "https://render.alipay.com/p/s/ctrip",
        "app_url": "alipays://platformapi/startapp?appId=20001197&page=pages/home/index",
        "source_type": "manual",
    },

    # ===================================================
    # 同程旅行 (2)
    # ===================================================
    {
        "id": "act_dy_tongcheng_99",
        "title": "同程旅行抖音券 99元机票盲盒",
        "platform": "抖音",
        "merchant_name": "同程旅行",
        "category": "出行旅游",
        "product_name": "同程机票盲盒",
        "original_price": 500.0,
        "activity_price": 99.0,
        "discount_description": "99元机票盲盒，随机目的地",
        "usage_conditions": "抖音App下单，同程App兑换",
        "valid_to": _days(15),
        "source_url": "https://www.douyin.com/search/%E5%90%8C%E7%A8%8B%E6%97%85%E8%A1%8C%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E5%90%8C%E7%A8%8B%E6%97%85%E8%A1%8C%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
    {
        "id": "act_mt_tongcheng_59",
        "title": "同程旅行美团券 59元酒店券",
        "platform": "美团",
        "merchant_name": "同程旅行",
        "category": "出行旅游",
        "product_name": "同程酒店券",
        "original_price": 159.0,
        "activity_price": 59.0,
        "discount_description": "59元酒店券，可兑换快捷酒店",
        "usage_conditions": "美团App下单，同程兑换",
        "valid_to": _days(30),
        "source_url": "https://i.meituan.com/s/%E5%90%8C%E7%A8%8B%E6%97%85%E8%A1%8C/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=同程旅行",
        "source_type": "manual",
    },

    # ===================================================
    # T3出行 (1)
    # ===================================================
    {
        "id": "act_dy_t3_8",
        "title": "T3出行抖音券 8折券",
        "platform": "抖音",
        "merchant_name": "T3出行",
        "category": "出行旅游",
        "product_name": "T3出行折扣券",
        "original_price": 0.0,
        "activity_price": 0.0,
        "discount_description": "T3出行8折，最高减8元",
        "usage_conditions": "抖音App下单，T3出行App使用",
        "valid_to": _days(7),
        "source_url": "https://www.douyin.com/search/T3%E5%87%BA%E8%A1%8C%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/T3%E5%87%BA%E8%A1%8C%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },

    # ===================================================
    # 中国石化加油 (1)
    # ===================================================
    {
        "id": "act_mt_sinopec_10",
        "title": "中国石化美团券 满200减10",
        "platform": "美团",
        "merchant_name": "中国石化",
        "category": "出行旅游",
        "product_name": "中石化加油券",
        "original_price": 200.0,
        "activity_price": 190.0,
        "discount_description": "满200减10，全国中石化可用",
        "usage_conditions": "美团下单，易捷加油App/小程序",
        "valid_to": _days(14),
        "source_url": "https://i.meituan.com/s/%E4%B8%AD%E5%9B%BD%E7%9F%B3%E5%8C%96/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=中国石化",
        "source_type": "manual",
    },

    # ===================================================
    # 宜家 (1)
    # ===================================================
    {
        "id": "act_mt_ikea_300",
        "title": "宜家美团券 满300减30",
        "platform": "美团",
        "merchant_name": "宜家",
        "category": "超市便利",
        "product_name": "宜家满减券",
        "original_price": 300.0,
        "activity_price": 270.0,
        "discount_description": "满300减30，家居用品一站购",
        "usage_conditions": "美团下单，宜家门店自提",
        "valid_to": _days(30),
        "source_url": "https://i.meituan.com/s/%E5%AE%9C%E5%AE%B6/",
        "app_url": "imeituan://www.meituan.com/deal/search?keyword=宜家",
        "source_type": "manual",
    },

    # ===================================================
    # 迪卡侬 (1)
    # ===================================================
    {
        "id": "act_dy_decathlon_99",
        "title": "迪卡侬抖音券 满200减15",
        "platform": "抖音",
        "merchant_name": "迪卡侬",
        "category": "超市便利",
        "product_name": "迪卡侬满减券",
        "original_price": 200.0,
        "activity_price": 185.0,
        "discount_description": "满200减15，运动装备优惠",
        "usage_conditions": "抖音App下单，迪卡侬门店自提",
        "valid_to": _days(14),
        "source_url": "https://www.douyin.com/search/%E8%BF%AA%E5%8D%A1%E4%BE%AC%E5%9B%A2%E8%B4%AD?type=general",
        "app_url": "douyin://search/%E8%BF%AA%E5%8D%A1%E4%BE%AC%E5%9B%A2%E8%B4%AD?type=general",
        "source_type": "manual",
    },
]
