"""银行优惠种子数据：来自各行官网/官方公告/什么值得买汇总，人工整理核实。

更新方式：定期搜索各行最新活动，追加或更新条目（upsert by id）。
"""
from datetime import datetime

BANK_OFFERS = [
    # ============ 招商银行 ============
    {
        "id": "bo_cmb_001",
        "bank": "招商银行",
        "title": "周三5折抢美食代金券",
        "category": "美食",
        "description": "每周三10点，在掌上生活App 5折抢购美食代金券，覆盖全国众多连锁餐饮商户，饭票专区可用。",
        "discount_highlight": "5折",
        "how_to_join": "掌上生活App → 精选/生活 → 饭票 → 周三5折（每周三10点开抢）",
        "jump_url": "https://cc.cmbchina.com/",
        "valid_period": "每周三 10:00",
        "valid_to": None,
        "status": "常态活动",
        "applicable_cards": "招商银行信用卡",
        "source": "掌上生活App",
    },
    {
        "id": "bo_cmb_002",
        "bank": "招商银行",
        "title": "暑期出游专项：机票立减+酒店65折起",
        "category": "旅行酒店",
        "description": "去哪儿机票立减、飞猪酒店65折起、免费领至高888元酒店券、9.9元起购美食冰饮。",
        "discount_highlight": "至高888元券",
        "how_to_join": "掌上生活App 搜索「暑期出游」",
        "jump_url": "https://cc.cmbchina.com/",
        "valid_period": "2026年暑期",
        "valid_to": datetime(2026, 8, 31, 23, 59, 59),
        "status": "进行中",
        "applicable_cards": "招商银行信用卡",
        "source": "招商银行信用卡官方微博",
    },
    # ============ 工商银行 ============
    {
        "id": "bo_icbc_001",
        "bank": "工商银行",
        "title": "工银e生活 刷卡金天天抽",
        "category": "返现",
        "description": "每天上午9:30起，登录工银e生活App参与抽奖，奖品含0.18/0.88/8.8元刷卡金及最高50元分期优惠券，每月400万份名额。",
        "discount_highlight": "天天可抽",
        "how_to_join": "工银e生活App 或 e生活plus小程序 → 刷卡金天天抽（每日9:30）",
        "jump_url": "https://www.icbc.com.cn/",
        "valid_period": "2026-07-01 至 2026-09-30",
        "valid_to": datetime(2026, 9, 30, 23, 59, 59),
        "status": "进行中",
        "applicable_cards": "工商银行信用卡",
        "source": "工银e生活",
    },
    {
        "id": "bo_icbc_002",
        "bank": "工商银行",
        "title": "工银爱旅行 随机一分游",
        "category": "旅行酒店",
        "description": "持工行银联「爱旅行」系列卡在航空、酒店、乐园、餐饮、免税店五大场景近万家商户消费，随机立减至高免4999元。",
        "discount_highlight": "至高免4999元",
        "how_to_join": "使用爱旅行系列卡于指定渠道商户消费即有机会立减",
        "jump_url": "https://www.icbc.com.cn/",
        "valid_period": "至 2026-12-31",
        "valid_to": datetime(2026, 12, 31, 23, 59, 59),
        "status": "进行中",
        "applicable_cards": "工行银联爱旅行系列卡",
        "source": "工行信用卡公告",
    },
    {
        "id": "bo_icbc_003",
        "bank": "工商银行",
        "title": "支付宝信用卡还款立减",
        "category": "生活",
        "description": "支付宝还工行信用卡，满2000元随机立减1-8元，每月限1次。",
        "discount_highlight": "减1-8元",
        "how_to_join": "支付宝 → 信用卡还款 → 选择工行卡支付",
        "jump_url": "https://www.icbc.com.cn/",
        "valid_period": "每月限1次",
        "valid_to": None,
        "status": "常态活动",
        "applicable_cards": "工商银行信用卡",
        "source": "银行活动汇总",
    },
    # ============ 兴业银行 ============
    {
        "id": "bo_cib_001",
        "bank": "兴业银行",
        "title": "兴业生活付款码消费随机减",
        "category": "返现",
        "description": "每日使用兴业生活App付款码到店消费，满5元随机减0.3-5元，每月限4次。",
        "discount_highlight": "至高减5元",
        "how_to_join": "兴业生活App → 付款码 → 到店消费",
        "jump_url": "https://creditcard.cib.com.cn/",
        "valid_period": "每月限4次",
        "valid_to": None,
        "status": "常态活动",
        "applicable_cards": "兴业银行信用卡",
        "source": "兴业生活App",
    },
    {
        "id": "bo_cib_002",
        "bank": "兴业银行",
        "title": "京东/淘宝消费满减",
        "category": "购物",
        "description": "通过兴业生活App在京东/淘宝-天猫超市消费，满100元减2-20元，每月各限1次；朴朴超市满50减2-20元。",
        "discount_highlight": "满100减20",
        "how_to_join": "兴业生活App → 京东/淘宝/朴朴超市 入口下单",
        "jump_url": "https://creditcard.cib.com.cn/",
        "valid_period": "每月限次",
        "valid_to": None,
        "status": "常态活动",
        "applicable_cards": "兴业银行信用卡",
        "source": "兴业生活App",
    },
    {
        "id": "bo_cib_003",
        "bank": "兴业银行",
        "title": "12306购票满减",
        "category": "出行",
        "description": "通过兴业生活App在12306购票，满150元减2-20元，每月限4次。",
        "discount_highlight": "满150减20",
        "how_to_join": "兴业生活App → 12306 入口购票",
        "jump_url": "https://creditcard.cib.com.cn/",
        "valid_period": "每月限4次",
        "valid_to": None,
        "status": "常态活动",
        "applicable_cards": "兴业银行信用卡",
        "source": "兴业生活App",
    },
    {
        "id": "bo_cib_004",
        "bank": "兴业银行",
        "title": "滴滴支付首绑至高减20元",
        "category": "出行",
        "description": "通过银行渠道首次将兴业信用卡绑定滴滴支付，消费至高立减20元。",
        "discount_highlight": "至高减20元",
        "how_to_join": "滴滴App → 支付 → 绑定兴业信用卡（首次）",
        "jump_url": "https://creditcard.cib.com.cn/",
        "valid_period": "2026年7月-12月",
        "valid_to": datetime(2026, 12, 31, 23, 59, 59),
        "status": "进行中",
        "applicable_cards": "兴业银行信用卡",
        "source": "兴业银行信用卡细则",
    },
    {
        "id": "bo_cib_005",
        "bank": "兴业银行",
        "title": "周周有金喜 周消费满600抽奖",
        "category": "返现",
        "description": "每周消费累计满600元，可到兴业生活App领取1次抽奖机会，抽2-10元刷卡金券包。",
        "discount_highlight": "周周可抽",
        "how_to_join": "兴业生活App → 周周有金喜（达标后次周周日前抽奖）",
        "jump_url": "https://creditcard.cib.com.cn/",
        "valid_period": "每周一次",
        "valid_to": None,
        "status": "常态活动",
        "applicable_cards": "兴业银行信用卡",
        "source": "兴业生活App",
    },
    # ============ 平安银行 ============
    {
        "id": "bo_pab_001",
        "bank": "平安银行",
        "title": "周周领好礼 抽微信立减金",
        "category": "返现",
        "description": "每周三0点起，平安口袋银行App「周周领好礼」抽1.08-88.88元微信立减金，每周限1次。",
        "discount_highlight": "至高88.88元",
        "how_to_join": "平安口袋银行App → 周周领好礼（每周三0点）",
        "jump_url": "https://bank.pingan.com/",
        "valid_period": "每周三",
        "valid_to": None,
        "status": "常态活动",
        "applicable_cards": "平安银行信用卡",
        "source": "平安口袋银行App",
    },
    # ============ 农业银行 ============
    {
        "id": "bo_abc_001",
        "bank": "农业银行",
        "title": "唯品会首绑立减3元",
        "category": "购物",
        "description": "唯品会App首次绑定农行信用卡并使用唯品支付，实付满3.01元立减3元。",
        "discount_highlight": "立减3元",
        "how_to_join": "唯品会App → 收银台 → 唯品支付 → 首次绑定农行卡支付",
        "jump_url": "https://www.abchina.com/cn/CreditCard/",
        "valid_period": "2026-07-01 至 2026-09-30",
        "valid_to": datetime(2026, 9, 30, 23, 59, 59),
        "status": "进行中",
        "applicable_cards": "农业银行信用卡（准贷记卡/单位卡除外）",
        "source": "农行信用卡公告",
    },
    # ============ 光大银行 ============
    {
        "id": "bo_ceb_001",
        "bank": "光大银行",
        "title": "支付宝分期立减",
        "category": "购物",
        "description": "光大信用卡在支付宝分期支付有机会享立减优惠。",
        "discount_highlight": "分期立减",
        "how_to_join": "支付宝收银台 → 选择光大信用卡分期支付",
        "jump_url": "https://xyk.cebbank.com/",
        "valid_period": "2026年7月-9月",
        "valid_to": datetime(2026, 9, 30, 23, 59, 59),
        "status": "进行中",
        "applicable_cards": "光大银行信用卡",
        "source": "光大信用卡公告",
    },
    {
        "id": "bo_ceb_002",
        "bank": "光大银行",
        "title": "淘宝分期免息+至高减20元",
        "category": "购物",
        "description": "淘宝下单选择光大信用卡分期，有机会享精选品牌免息和至高减20元。",
        "discount_highlight": "至高减20元",
        "how_to_join": "淘宝 → 收银台 → 光大信用卡分期",
        "jump_url": "https://xyk.cebbank.com/",
        "valid_period": "2026年8月",
        "valid_to": datetime(2026, 8, 31, 23, 59, 59),
        "status": "进行中",
        "applicable_cards": "光大银行信用卡",
        "source": "光大信用卡公告",
    },
    # ============ 邮储银行 ============
    {
        "id": "bo_psbc_001",
        "bank": "邮储银行",
        "title": "新户开卡礼208元立减金礼包",
        "category": "开卡礼",
        "description": "新户成功核发指定邮储信用卡并激活，可领208元微信立减金礼包或208元支付宝红包礼包（含30元券+89天每日2元券）。",
        "discount_highlight": "208元礼包",
        "how_to_join": "邮储银行App → 信用卡 → 信用卡活动 → 新客开卡礼（激活7天内领取）",
        "jump_url": "https://www.psbc.com/",
        "valid_period": "限量144021份",
        "valid_to": datetime(2026, 8, 31, 23, 59, 59),
        "status": "进行中",
        "applicable_cards": "邮储银行指定信用卡新户",
        "source": "邮储银行信用卡中心",
    },
    {
        "id": "bo_psbc_002",
        "bank": "邮储银行",
        "title": "越刷越精彩 消费达标领好礼",
        "category": "返现",
        "description": "手机银行/小程序报名后，累计消费满指定门槛可领取权益，名额有限先领先得。",
        "discount_highlight": "万元好礼",
        "how_to_join": "邮储银行App → 信用卡 → 越刷越精彩 报名",
        "jump_url": "https://www.psbc.com/",
        "valid_period": "2026年7月-9月",
        "valid_to": datetime(2026, 9, 30, 23, 59, 59),
        "status": "进行中",
        "applicable_cards": "邮储银行信用卡主卡",
        "source": "邮储银行信用卡中心",
    },
    # ============ 广州银行 ============
    {
        "id": "bo_gzcb_001",
        "bank": "广州银行",
        "title": "支付宝/抖音/京东首绑立减6.6元",
        "category": "购物",
        "description": "历史首次将广州银行信用卡绑定支付宝、抖音、京东，绑卡后首次消费满6.6元立减6.6元，每个平台限1次。",
        "discount_highlight": "减6.6元×3平台",
        "how_to_join": "支付宝/抖音/京东 → 绑定广州银行信用卡 → 首笔消费",
        "jump_url": "https://www.gzcb.com.cn/",
        "valid_period": "名额有限",
        "valid_to": datetime(2026, 12, 31, 23, 59, 59),
        "status": "进行中",
        "applicable_cards": "广州银行信用卡",
        "source": "广州银行公告",
    },
    {
        "id": "bo_gzcb_002",
        "bank": "广州银行",
        "title": "中石化加油满200减20",
        "category": "出行",
        "description": "韶关自营中石化门店，微信支付选广州银行信用卡，满200元立减20元，每日1次每月2次。",
        "discount_highlight": "满200减20",
        "how_to_join": "韶关中石化门店 → 微信支付 → 广州银行信用卡",
        "jump_url": "https://www.gzcb.com.cn/",
        "valid_period": "每月限2次",
        "valid_to": datetime(2026, 12, 31, 23, 59, 59),
        "status": "进行中",
        "applicable_cards": "广州银行信用卡",
        "source": "广州银行公告",
    },
    # ============ 重庆银行 ============
    {
        "id": "bo_cqcb_001",
        "bank": "重庆银行",
        "title": "5元洗车",
        "category": "出行",
        "description": "手机银行在线支付5元购买洗车券，1个月内到线下指定门店享受普通洗车服务。",
        "discount_highlight": "5元洗车",
        "how_to_join": "重庆银行手机银行 → 5元洗车活动页购买洗车券",
        "jump_url": "https://www.cqcbank.com/",
        "valid_period": "2026年",
        "valid_to": datetime(2026, 12, 31, 23, 59, 59),
        "status": "进行中",
        "applicable_cards": "重庆银行指定信用卡",
        "source": "重庆银行公告",
    },
    # ============ 深圳农商银行 ============
    {
        "id": "bo_srcb_001",
        "bank": "深圳农商银行",
        "title": "周一早餐100%返现免单",
        "category": "美食",
        "description": "每周一6:00-11:00在真功夫、永和大王指定门店，微信支付满额100%返现，单笔最高返6元，每日限300名额。",
        "discount_highlight": "最高返6元",
        "how_to_join": "周一早6-11点 指定门店 → 微信支付 → 深圳农商银行卡（返现60天内领取）",
        "jump_url": "https://www.4001961200.com/",
        "valid_period": "每周一",
        "valid_to": datetime(2026, 12, 31, 23, 59, 59),
        "status": "进行中",
        "applicable_cards": "深圳农商银行信用卡",
        "source": "深圳农商银行权益通知",
    },
    {
        "id": "bo_srcb_002",
        "bank": "深圳农商银行",
        "title": "周二周三滴滴出行立减",
        "category": "出行",
        "description": "每周二、周三使用滴滴出行并以深圳农商银行信用卡支付，享立减优惠。",
        "discount_highlight": "出行立减",
        "how_to_join": "滴滴App → 支付选择深圳农商银行卡（周二/周三）",
        "jump_url": "https://www.4001961200.com/",
        "valid_period": "每周二、周三",
        "valid_to": datetime(2026, 12, 31, 23, 59, 59),
        "status": "进行中",
        "applicable_cards": "深圳农商银行信用卡",
        "source": "深圳农商银行权益通知",
    },
    # ============ 北京银行 ============
    {
        "id": "bo_bob_001",
        "bank": "北京银行",
        "title": "bilibili联名卡新户领50元立减金",
        "category": "开卡礼",
        "description": "美国运通bilibili联名卡新户核卡30天内激活，登录掌上京彩App领取50元微信立减金。",
        "discount_highlight": "50元立减金",
        "how_to_join": "激活卡片 → 掌上京彩App 领取",
        "jump_url": "https://creditcard.bankofbeijing.com.cn/",
        "valid_period": "2026年7月-9月核卡",
        "valid_to": datetime(2026, 9, 30, 23, 59, 59),
        "status": "进行中",
        "applicable_cards": "北京银行美国运通bilibili联名卡新户",
        "source": "北京银行公告",
    },
]
